services:
  - type: web
    name: sp500-analysis
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 300
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
      - key: MAX_CONTENT_LENGTH
        value: 52428800
      - key: CORS_ORIGINS
        value: "*"
      - key: SECRET_KEY
        generateValue: true
